### ISSUE TITLE
Pip Install Problem

### ISSUE THREAD

**Issue by santiagohuerdo** [jbn/ZigZag#32]
Hi, when i try to install zigzag with `pip install zigzag` i receive this error

![image](https://user-images.githubusercontent.com/90464580/208469637-f5922ada-4a09-4ed6-82af-d7ce6717ee95.png)

thanks

**Comment by playbonze** [comment]
i have the same problem

**Comment by playbonze** [comment]
Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: Cython<0.30,>=0.29 in c:\veighna_studio\lib\site-packages (from zigzag) (0.29.32)
Requirement already satisfied: numpy>=1.21.1 in c:\veighna_studio\lib\site-packages (from zigzag) (1.23.4)
Building wheels for collected packages: zigzag
  Building wheel for zigzag (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for zigzag (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [58 lines of output]
      C:\Users\playbonze\AppData\Local\Temp\pip-install-4s7ay493\zigzag_b9fc7ec310fc4a2b8cc03a242b09d568\build.py:4: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
        from distutils.command.build_ext import build_ext
      warning: zigzag\core.pyx:5:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: zigzag\core.pyx:6:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      Compiling zigzag\core.pyx because it changed.
      [1/1] Cythonizing zigzag\core.pyx
      cl: 命令行 warning D9002 :忽略未知选项“-O3”
      core.c
      C:\veighna_studio\include\pyconfig.h(59): fatal error C1083: 无法打开包括文件: “io.h”: No such file or directory
      Traceback (most recent call last):
        File "C:\veighna_studio\lib\distutils\_msvccompiler.py", line 401, in compile
          self.spawn(args)
        File "C:\veighna_studio\lib\distutils\_msvccompiler.py", line 507, in spawn
          return super().spawn(cmd)
        File "C:\veighna_studio\lib\distutils\ccompiler.py", line 910, in spawn
          spawn(cmd, dry_run=self.dry_run)
        File "C:\veighna_studio\lib\distutils\spawn.py", line 91, in spawn
          raise DistutilsExecError(
      distutils.errors.DistutilsExecError: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\playbonze\AppData\Local\Temp\pip-install-4s7ay493\zigzag_b9fc7ec310fc4a2b8cc03a242b09d568\build.py", line 55, in <module>
          build()
        File "C:\Users\playbonze\AppData\Local\Temp\pip-install-4s7ay493\zigzag_b9fc7ec310fc4a2b8cc03a242b09d568\build.py", line 43, in build
          cmd.run()
        File "C:\veighna_studio\lib\distutils\command\build_ext.py", line 340, in run
          self.build_extensions()
        File "C:\veighna_studio\lib\distutils\command\build_ext.py", line 449, in build_extensions
          self._build_extensions_serial()
        File "C:\veighna_studio\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
          self.build_extension(ext)
        File "C:\veighna_studio\lib\distutils\command\build_ext.py", line 529, in build_extension
          objects = self.compiler.compile(sources,
        File "C:\veighna_studio\lib\distutils\_msvccompiler.py", line 403, in compile
          raise CompileError(msg)
      distutils.errors.CompileError: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      Traceback (most recent call last):
        File "C:\veighna_studio\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
          main()
        File "C:\veighna_studio\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\veighna_studio\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 249, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\Users\playbonze\AppData\Local\Temp\pip-build-env-3agj2ise\overlay\Lib\site-packages\poetry\core\masonry\api.py", line 56, in build_wheel
          return WheelBuilder.make_in(
        File "C:\Users\playbonze\AppData\Local\Temp\pip-build-env-3agj2ise\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 85, in make_in
          wb.build(target_dir=directory)
        File "C:\Users\playbonze\AppData\Local\Temp\pip-build-env-3agj2ise\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 120, in build
          self._build(zip_file)
        File "C:\Users\playbonze\AppData\Local\Temp\pip-build-env-3agj2ise\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 169, in _build
          self._run_build_script(self._package.build_script)
        File "C:\Users\playbonze\AppData\Local\Temp\pip-build-env-3agj2ise\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 229, in _run_build_script
          subprocess.check_call([self.executable.as_posix(), build_script])
        File "C:\veighna_studio\lib\subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['C:/veighna_studio/python.exe', 'build.py']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for zigzag
Failed to build zigzag
ERROR: Could not build wheels for zigzag, which is required to install pyproject.toml-based projects

**Comment by playbonze** [comment]
i finally solve the problem. install visual studio 2022 community, pick 2 component: MSVC v143、windows 10 SDK.

**Comment by ozturkeyupp54** [comment]
@playbonze you are the best!!

**Comment by Sithipath41** [comment]
Hi, thanks for sharing, I have the same problem with anaconda, so I try using vs code instead and pick 2 component: MSVC v143、windows 10 SDK in individual component. Then I got the error below 

PS C:\Users\sithi\source\repos\Test> pip install zigzag
Collecting zigzag
  Using cached https://files.pythonhosted.org/packages/d4/88/028c3d29b17cd2d4cfcc2305bc42e0363d64451e3eda880aab1d0e579069/zigzag-0.3.2.tar.gz
ERROR: Exception:
Traceback (most recent call last):
  File "c:\users\sithi\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\cli\base_command.py", line 188, in main
    status = self.run(options, args)
  File "c:\users\sithi\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\commands\install.py", line 345, in run
    resolver.resolve(requirement_set)
  File "c:\users\sithi\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\legacy_resolve.py", line 196, in resolve
    self._resolve_one(requirement_set, req)
  File "c:\users\sithi\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\legacy_resolve.py", line 359, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "c:\users\sithi\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\legacy_resolve.py", line 305, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(
  File "c:\users\sithi\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\operations\prepare.py", line 214, in prepare_linked_requirement
    abstract_dist.prepare_distribution_metadata(
  File "c:\users\sithi\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\distributions\source.py", line 30, in prepare_distribution_metadata
    self.req.load_pyproject_toml()
  File "c:\users\sithi\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\req\req_install.py", line 501, in load_pyproject_toml
    pyproject_toml_data = load_pyproject_toml(
  File "c:\users\sithi\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\pyproject.py", line 66, in load_pyproject_toml
    pp_toml = pytoml.load(f)
  File "c:\users\sithi\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\pytoml\parser.py", line 11, in load
    return loads(fin.read(), translate=translate, object_pairs_hook=object_pairs_hook, filename=getattr(fin, 'name', repr(fin)))
  File "c:\users\sithi\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\pytoml\parser.py", line 46, in loads
    scope[k] = process_value(v, object_pairs_hook=object_pairs_hook)
  File "c:\users\sithi\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\pytoml\parser.py", line 35, in process_value
    error('array-type-mismatch')
  File "c:\users\sithi\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\pytoml\parser.py", line 27, in error
    raise TomlError(msg, pos[0], pos[1], filename)
pip._vendor.pytoml.core.TomlError: C:\Users\sithi\AppData\Local\Temp\pip-install-vknd330m\zigzag\pyproject.toml(19, 1): array-type-mismatch
WARNING: You are using pip version 19.2.3, however version 22.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

Please let me know if you have any idea on how to troubleshoot this error. Thanks

**Comment by alxbar75** [comment]
I also had problems with `pip install zigzag`. What solved it for me was:

1. pip install Cython
2. sudo apt install python3.10-dev (I'm on Ubuntu using Python 3.10)

Maybe this helps someone.
